public = "public"
domain = "http://localhost:8081"
session_secret = "session-secret-phrase"
signup_enabled = true

[database]
host = "127.0.0.1"
port = 3306
name = "goweb"
user = "root"
password = "root"

[smtp]
from = "your@email.com"
smtp = "smtp.email.com"
port = 465
user = "your@email.com"
password = "email_password"
